# Generated by Django 3.1 on 2020-09-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20200831_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
